services:
  mysql:
    image: 'mysql:8.4'
    container_name: mysql_play
    environment:
      - 'MYSQL_DATABASE=playconnect_db'
      - 'MYSQL_PASSWORD=Topone147258#'
      - 'MYSQL_ROOT_PASSWORD=Topone147258#'
      - 'MYSQL_USER=playconnect'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local